com_port: auto
baud_rate: 921600
invert_sliders: false
slider_mapping:
- master
- communication
- media
- games
button_mapping:
- smtc_previous
- smtc_play_pause
- smtc_next
- discord_mute
- discord_deafen
session_groups:
  games:
  - ELDEN RING
  - Fallout 76 Public Test Server
  - Green Hell
  - Icarus
  - Iron Snout
  - Portal 2
  - Project Zomboid
  - Raft
  - Starbound
  - Terraria
  - DayZ
  - Fallout 76
  - Bloons TD 6
  media:
  - Chrome
  - Brave
  - Spotify
  communication:
  - Discord
