com_port: auto
baud_rate: 921600
invert_sliders: false
slider_mapping:
- master
- communication
- media
- games
button_mapping:
- smtc_previous
- smtc_play_pause
- smtc_next
- discord_mute
- discord_deafen
session_groups:
  communication:
  - Discord
  - Teams
  - Teamspeak
  media:
  - Chrome
  - Brave
  - Spotify
  - Firefox
  - msedge
  games:
  - DayZ
  - Stardew Valley
  - Battlefield 6
  - Icarus
  - Rocket League
  - Enshrouded
  - Terraria
  - Rust
  - Diablo III
  - Steam
  - Battle.net
  - SlimeRancher
