com_port: auto
baud_rate: 921600
invert_sliders: false
slider_mapping:
- master
- communication
- media
- games
slider_response:
- center_flattened
- center_flattened
- center_flattened
- center_flattened
button_mapping:
- smtc_previous
- smtc_play_pause
- smtc_next
- discord_mute
- discord_deafen
session_groups:
  master: []
  media:
  - Brave
  - Chrome
  - Spotify
  communication:
  - Discord
  games:
  - 'Batman™: Arkham Knight'
  - DayZ
  - Diablo III
  - ELDEN RING
  - Factorio
  - 'FAR: Changing Tides'
  - Green Hell
  - Icarus
  - League Of Legends
  - PAYDAY 2
  - Portal 2
  - Project Zomboid
  - 'PUBG: BATTLEGROUNDS'
  - Raft
  - Rocket League®
  - Starbound
  - Terraria
  - tModLoader
  - Valorant
limit_system_sounds_to_20_percent: true
igdb: 
